# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exprompt < Formula
  desc "Free, open-source CLI prompt compressor for LLMs."
  homepage "https://github.com/bladysh/exprompt"
  version "0.6.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bladysh/exprompt/releases/download/v0.6.10/exprompt_0.6.10_darwin_amd64.tar.gz"
      sha256 "629fe393ee567a73faee22fe99723466fb89529c5b377c4cde6472835007ebac"

      define_method(:install) do
        bin.install "exprompt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bladysh/exprompt/releases/download/v0.6.10/exprompt_0.6.10_darwin_arm64.tar.gz"
      sha256 "dc616102938b0761855cda98efa782c2e06ec1ac29344686c27850249c7d208c"

      define_method(:install) do
        bin.install "exprompt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bladysh/exprompt/releases/download/v0.6.10/exprompt_0.6.10_linux_amd64.tar.gz"
      sha256 "07aa89fdefcbd5fc1f04e9f65cb44f7ae15f042329853730f1ed0d9d85d417cd"
      define_method(:install) do
        bin.install "exprompt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bladysh/exprompt/releases/download/v0.6.10/exprompt_0.6.10_linux_arm64.tar.gz"
      sha256 "93f14802c0b2e9045a43bd7f4e5dc1565f13754b80ed68f3af5d338e1708fa8b"
      define_method(:install) do
        bin.install "exprompt"
      end
    end
  end

  test do
    system "#{bin}/exprompt", "--version"
  end
end
